### ISSUE TITLE
Python CHCP on Windows

### ISSUE THREAD

**Issue by Artorp** [TheThingy/TradeIT#2]
If Windows has default CHCP of 437, python tracebacks.

```
Per@TromsTraceback (most recent call last):
  File ".\TradeIT.py", line 65, in <module>
    game.mainloop()
  File ".\TradeIT.py", line 57, in mainloop
    self.view.render()
  File "D:\GitHub-Repos\TradeIT\render.py", line 33, in render
    print(char, end="")
  File "C:\Python\Python35-64\lib\encodings\cp437.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\xf8' in position 0: character maps to <undefined>
```

Workaround right now is to set Code Page to 65001 (UTF-8) manually:
```
chcp 65001
python TradeIT.py
```

Todo: Change this from within Python??

**Comment by Artorp** [comment]
In retrospect, this is an issue with the windows terminal not using the UTF-8 encoding. If users of windows terminal wants to run this program, they should change their codepage themselves.

PS: Powershell supports profiles, add `chcp 65001` to powershell profile to load UTF-8 codepage when opening powershell.

Closed.
